//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ЕРЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Застрахованное_лицо
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Застрахованное_лицо()
        {
            this.ДПФС = new HashSet<ДПФС>();
            this.Персоналные_данные = new HashSet<Персоналные_данные>();
            this.Состтояние_на_учёте = new HashSet<Состтояние_на_учёте>();
        }
    
        public int ID_ЗЛ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДПФС> ДПФС { get; set; }
        public virtual Застрахованное_лицо Застрахованное_лицо1 { get; set; }
        public virtual Застрахованное_лицо Застрахованное_лицо2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Персоналные_данные> Персоналные_данные { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состтояние_на_учёте> Состтояние_на_учёте { get; set; }
    }
}
