//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ЕРЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Персоналные_данные
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Пол { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public System.DateTime Дата_смерти { get; set; }
        public string Тип_документа { get; set; }
        public string Номер { get; set; }
        public string ЕНП { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public string Серия { get; set; }
        public Nullable<int> ID_ЗЛ { get; set; }
        public int Id { get; set; }
    
        public virtual Застрахованное_лицо Застрахованное_лицо { get; set; }
    }
}
