//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ИС_ЕРЗ
{
    using System;
    using System.Collections.Generic;
    
    public partial class СМО
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СМО()
        {
            this.Состтояние_на_учёте = new HashSet<Состтояние_на_учёте>();
        }
    
        public int ID_СМО { get; set; }
        public string Название { get; set; }
        public int Код_субъекта { get; set; }
        public string Субъект_федерации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состтояние_на_учёте> Состтояние_на_учёте { get; set; }
    }
}
